### ISSUE TITLE
Dropdown's are not reactive in Example Forum

### ISSUE THREAD

**Issue by drpears** [VulcanJS/Vulcan-Starter#105]
I'm using the Example Forum package and am seeing the warning below in the console along with the Dropdown component being non responsive. 
![image](https://user-images.githubusercontent.com/16214147/50565375-e16b4280-0cf3-11e9-9fa0-cd6cd602c5be.png)

There's no warnings or errors thrown in the console related to this issue. I would debug further but it seems that it's a core vulcan ui component and I'm not to familiar with the entirety of the architecture yet.

I appreciate any help, thanks!

Dylan

**Comment by drpears** [comment]
Here's a screen record of the non responsive behavior [Uploaded Video](https://www.youtube.com/watch?v=mkz_FU6bB6o&feature=youtu.be)

**Comment by SachaG** [comment]
Looks like an error due to the recent react-bootstrap/Bootstrap 4 update. I'll look into it, thanks!

**Comment by drpears** [comment]
@SachaG  great thank you

**Comment by SachaG** [comment]
Should be fixed; I just need to push a new version (1.12.13) of the core Vulcan packages and it should be fine :)

**Comment by drpears** [comment]
@SachaG Updated the core packages to 1.12.13 and I'm still seeing an issue with the bootstrap related components. Could you point me to which of the core packages I could take a look at and debug?

**Comment by drpears** [comment]
@SachaG Did the changes you made when you pushed to 1.12.13 fix it on your side?

**Comment by SachaG** [comment]
Yes but you also have to pull the latest changes from this repo.

**Comment by yairtal** [comment]
Try cloning the repo again and then:
`meteor update`
`yarn install`
`yarn start`

**Comment by fedriz** [comment]
I'm using the getting-started-completed branch, it's kinda working, try it
