### ISSUE TITLE
Can't register: Internal server error

### ISSUE THREAD

**Issue by yairtal** [VulcanJS/Vulcan-Starter#112]
Open example-forum, try to register as a new first user.
Internal server error.
Exception while invoking method 'createUser' TypeError: Cannot read property 'username' of undefined
at Object.onCreate (packages/vulcan:users/lib/modules/schema.js:59:18)

**Comment by SachaG** [comment]
Sorry about that, should be fixed in version 1.12.15.

**Comment by yairtal** [comment]
Not fixed, after a clean install, I am still getting the same error.
Steps to reproduce: clone, meteor update, yarn install, change to example-forum package, yarn start.

**Comment by SachaG** [comment]
Hmm, weird. How about if you update `vulcan:users` to `1.12.16`?

**Comment by yairtal** [comment]
1.12.16 fixed the problem, thanks
